/* mehPL:
 *    This is Open Source, but NOT GPL. I call it mehPL.
 *    I'm not too fond of long licenses at the top of the file.
 *    Please see the bottom.
 *    Enjoy!
 */




//This file contains consecutive writeColor calls
// in such a way that they'll be optimized not to use pointer-arithmetic,
// nor a for-loop which requires counters, jumps, and tests that take quite
// a bit of overhead

//This file was mostly generated by _tools/createUnrolledLoop.sh
// But had to be hand-modified (and that script probably won't run on your
// system as-is, as it depends on other scripts I have)


#if(!defined(FB_WIDTH) || (FB_WIDTH > 64) || FB_WIDTH < 2)
 #error "FB_WIDTH needs to be a defined value from 2 to 64"
#else

#if(FB_WIDTH>=(2))
  writeColor(FALSE,TRUE, *(color+1));
#endif
#if(FB_WIDTH>=(3))
  writeColor(FALSE,TRUE, *(color+2));
#endif
#if(FB_WIDTH>=(4))
  writeColor(FALSE,TRUE, *(color+3));
#endif
#if(FB_WIDTH>=(5))
  writeColor(FALSE,TRUE, *(color+4));
#endif
#if(FB_WIDTH>=(6))
  writeColor(FALSE,TRUE, *(color+5));
#endif
#if(FB_WIDTH>=(7))
  writeColor(FALSE,TRUE, *(color+6));
#endif
#if(FB_WIDTH>=(8))
  writeColor(FALSE,TRUE, *(color+7));
#endif
#if(FB_WIDTH>=(9))
  writeColor(FALSE,TRUE, *(color+8));
#endif
#if(FB_WIDTH>=(10))
  writeColor(FALSE,TRUE, *(color+9));
#endif
#if(FB_WIDTH>=(11))
  writeColor(FALSE,TRUE, *(color+10));
#endif
#if(FB_WIDTH>=(12))
  writeColor(FALSE,TRUE, *(color+11));
#endif
#if(FB_WIDTH>=(13))
  writeColor(FALSE,TRUE, *(color+12));
#endif
#if(FB_WIDTH>=(14))
  writeColor(FALSE,TRUE, *(color+13));
#endif
#if(FB_WIDTH>=(15))
  writeColor(FALSE,TRUE, *(color+14));
#endif
#if(FB_WIDTH>=(16))
  writeColor(FALSE,TRUE, *(color+15));
#endif
#if(FB_WIDTH>=(17))
  writeColor(FALSE,TRUE, *(color+16));
#endif
#if(FB_WIDTH>=(18))
  writeColor(FALSE,TRUE, *(color+17));
#endif
#if(FB_WIDTH>=(19))
  writeColor(FALSE,TRUE, *(color+18));
#endif
#if(FB_WIDTH>=(20))
  writeColor(FALSE,TRUE, *(color+19));
#endif
#if(FB_WIDTH>=(21))
  writeColor(FALSE,TRUE, *(color+20));
#endif
#if(FB_WIDTH>=(22))
  writeColor(FALSE,TRUE, *(color+21));
#endif
#if(FB_WIDTH>=(23))
  writeColor(FALSE,TRUE, *(color+22));
#endif
#if(FB_WIDTH>=(24))
  writeColor(FALSE,TRUE, *(color+23));
#endif
#if(FB_WIDTH>=(25))
  writeColor(FALSE,TRUE, *(color+24));
#endif
#if(FB_WIDTH>=(26))
  writeColor(FALSE,TRUE, *(color+25));
#endif
#if(FB_WIDTH>=(27))
  writeColor(FALSE,TRUE, *(color+26));
#endif
#if(FB_WIDTH>=(28))
  writeColor(FALSE,TRUE, *(color+27));
#endif
#if(FB_WIDTH>=(29))
  writeColor(FALSE,TRUE, *(color+28));
#endif
#if(FB_WIDTH>=(30))
  writeColor(FALSE,TRUE, *(color+29));
#endif
#if(FB_WIDTH>=(31))
  writeColor(FALSE,TRUE, *(color+30));
#endif
#if(FB_WIDTH>=(32))
  writeColor(FALSE,TRUE, *(color+31));
#endif
#if(FB_WIDTH>=(33))
  writeColor(FALSE,TRUE, *(color+32));
#endif
#if(FB_WIDTH>=(34))
  writeColor(FALSE,TRUE, *(color+33));
#endif
#if(FB_WIDTH>=(35))
  writeColor(FALSE,TRUE, *(color+34));
#endif
#if(FB_WIDTH>=(36))
  writeColor(FALSE,TRUE, *(color+35));
#endif
#if(FB_WIDTH>=(37))
  writeColor(FALSE,TRUE, *(color+36));
#endif
#if(FB_WIDTH>=(38))
  writeColor(FALSE,TRUE, *(color+37));
#endif
#if(FB_WIDTH>=(39))
  writeColor(FALSE,TRUE, *(color+38));
#endif
#if(FB_WIDTH>=(40))
  writeColor(FALSE,TRUE, *(color+39));
#endif
#if(FB_WIDTH>=(41))
  writeColor(FALSE,TRUE, *(color+40));
#endif
#if(FB_WIDTH>=(42))
  writeColor(FALSE,TRUE, *(color+41));
#endif
#if(FB_WIDTH>=(43))
  writeColor(FALSE,TRUE, *(color+42));
#endif
#if(FB_WIDTH>=(44))
  writeColor(FALSE,TRUE, *(color+43));
#endif
#if(FB_WIDTH>=(45))
  writeColor(FALSE,TRUE, *(color+44));
#endif
#if(FB_WIDTH>=(46))
  writeColor(FALSE,TRUE, *(color+45));
#endif
#if(FB_WIDTH>=(47))
  writeColor(FALSE,TRUE, *(color+46));
#endif
#if(FB_WIDTH>=(48))
  writeColor(FALSE,TRUE, *(color+47));
#endif
#if(FB_WIDTH>=(49))
  writeColor(FALSE,TRUE, *(color+48));
#endif
#if(FB_WIDTH>=(50))
  writeColor(FALSE,TRUE, *(color+49));
#endif
#if(FB_WIDTH>=(51))
  writeColor(FALSE,TRUE, *(color+50));
#endif
#if(FB_WIDTH>=(52))
  writeColor(FALSE,TRUE, *(color+51));
#endif
#if(FB_WIDTH>=(53))
  writeColor(FALSE,TRUE, *(color+52));
#endif
#if(FB_WIDTH>=(54))
  writeColor(FALSE,TRUE, *(color+53));
#endif
#if(FB_WIDTH>=(55))
  writeColor(FALSE,TRUE, *(color+54));
#endif
#if(FB_WIDTH>=(56))
  writeColor(FALSE,TRUE, *(color+55));
#endif
#if(FB_WIDTH>=(57))
  writeColor(FALSE,TRUE, *(color+56));
#endif
#if(FB_WIDTH>=(58))
  writeColor(FALSE,TRUE, *(color+57));
#endif
#if(FB_WIDTH>=(59))
  writeColor(FALSE,TRUE, *(color+58));
#endif
#if(FB_WIDTH>=(60))
  writeColor(FALSE,TRUE, *(color+59));
#endif
#if(FB_WIDTH>=(61))
  writeColor(FALSE,TRUE, *(color+60));
#endif
#if(FB_WIDTH>=(62))
  writeColor(FALSE,TRUE, *(color+61));
#endif
#if(FB_WIDTH>=(63))
  writeColor(FALSE,TRUE, *(color+62));
#endif
#if(FB_WIDTH>=(64))
  writeColor(FALSE,TRUE, *(color+63));
#endif

#define COLORS_WRITTEN (FB_WIDTH)
#endif
/* mehPL:
 *    I would love to believe in a world where licensing shouldn't be
 *    necessary; where people would respect others' work and wishes, 
 *    and give credit where it's due. 
 *    A world where those who find people's work useful would at least 
 *    send positive vibes--if not an email.
 *    A world where we wouldn't have to think about the potential
 *    legal-loopholes that others may take advantage of.
 *
 *    Until that world exists:
 *
 *    This software and associated hardware design is free to use,
 *    modify, and even redistribute, etc. with only a few exceptions
 *    I've thought-up as-yet (this list may be appended-to, hopefully it
 *    doesn't have to be):
 * 
 *    1) Please do not change/remove this licensing info.
 *    2) Please do not change/remove others' credit/licensing/copyright 
 *         info, where noted. 
 *    3) If you find yourself profiting from my work, please send me a
 *         beer, a trinket, or cash is always handy as well.
 *         (Please be considerate. E.G. if you've reposted my work on a
 *          revenue-making (ad-based) website, please think of the
 *          years and years of hard work that went into this!)
 *    4) If you *intend* to profit from my work, you must get my
 *         permission, first. 
 *    5) No permission is given for my work to be used in Military, NSA,
 *         or other creepy-ass purposes. No exceptions. And if there's 
 *         any question in your mind as to whether your project qualifies
 *         under this category, you must get my explicit permission.
 *
 *    The open-sourced project this originated from is ~98% the work of
 *    the original author, except where otherwise noted.
 *    That includes the "commonCode" and makefiles.
 *    Thanks, of course, should be given to those who worked on the tools
 *    I've used: avr-dude, avr-gcc, gnu-make, vim, usb-tiny, and 
 *    I'm certain many others. 
 *    And, as well, to the countless coders who've taken time to post
 *    solutions to issues I couldn't solve, all over the internets.
 *
 *
 *    I'd love to hear of how this is being used, suggestions for
 *    improvements, etc!
 *         
 *    The creator of the original code and original hardware can be
 *    contacted at:
 *
 *        EricWazHung At Gmail Dotcom
 *
 *    This code's origin (and latest versions) can be found at:
 *
 *        https://code.google.com/u/ericwazhung/
 *
 *    The site associated with the original open-sourced project is at:
 *
 *        https://sites.google.com/site/geekattempts/
 *
 *    If any of that ever changes, I will be sure to note it here, 
 *    and add a link at the pages above.
 *
 * This license added to the original file located at:
 * /Users/meh/_avrProjects/LCDdirectLVDS/90-reGitting/_options/fb_writeColorCalls.c
 *
 *    (Wow, that's a lot longer than I'd hoped).
 *
 *    Enjoy!
 */
