//Auto-generated by makefile

#ifndef __PROJINFO_H__
#define __PROJINFO_H__
#include <inttypes.h>

#if (!defined(PROJINFO_SHORT) || !PROJINFO_SHORT)
 uint8_t __attribute__ ((progmem)) \
   header0[] = " /Users/meh/_commonCode/heartbeat/1.30/testDMS ";
 uint8_t __attribute__ ((progmem)) \
   header1[] = " Sun Feb  9 21:50:00 PST 2014 ";
 uint8_t __attribute__ ((progmem)) \
   headerOpt[] = "  ";
#else //projInfo Shortened
 uint8_t __attribute__ ((progmem)) \
   header[] = "heartbeatTesttestDMS 2014-02-09 21:50:00";
#endif

//For internal use...
//Currently only usable in main.c
#define PROJ_VER testDMS
#define COMPILE_YEAR 2014

#endif

