//Auto-generated by makefile

#ifndef __PROJINFO_H__
#define __PROJINFO_H__
#include <inttypes.h>

#if (defined(_PROJINFO_OVERRIDE_) && _PROJINFO_OVERRIDE_)
 const uint8_t __attribute__ ((progmem)) \
   header[] = "";
#elif (defined(PROJINFO_SHORT) && PROJINFO_SHORT)
 const uint8_t __attribute__ ((progmem)) \
   header[] = "heartbeatTesttestPWM161 2014-04-21 19:50:09";
#else //projInfo Not Shortened nor overridden
 const uint8_t __attribute__ ((progmem)) \
   header0[] = " /Users/meh/_commonCode/heartbeat/1.30/testPWM161 ";
 const uint8_t __attribute__ ((progmem)) \
   header1[] = " Mon Apr 21 19:50:09 PDT 2014 ";
 const uint8_t __attribute__ ((progmem)) \
   headerOpt[] = "  ";
#endif

//For internal use...
//Currently only usable in main.c
#define PROJ_VER testPWM161
#define COMPILE_YEAR 2014

#endif

